# -*- coding: utf-8 -*-
'''
vdirsyncer is a synchronization tool for vdir. See the README for more details.
'''


try:
    from .version import version as __version__  # noqa
except ImportError:
    raise ImportError(
        'Failed to find (autogenerated) version.py. '
        'This might be because you are installing from GitHub\'s tarballs, '
        'use the PyPI ones.'
    )

PROJECT_HOME = 'https://github.com/untitaker/vdirsyncer'
DOCS_HOME = 'https://vdirsyncer.readthedocs.org/en/latest'
